export const AUTH_SIGNIN = 'AUTH_SIGNIN'
export const AUTH_SIGNIN_SUCCESS = 'AUTH_SIGNIN_SUCCESS'
export const AUTH_SIGNIN_FAIL = 'AUTH_SIGNIN_FAIL'

export const AUTH_SIGNOUT = 'AUTH_SIGNOUT'
export const AUTH_SIGNOUT_SUCCESS = 'AUTH_SIGNOUT_SUCCESS'
export const AUTH_SIGNOUT_FAIL = 'AUTH_SIGNOUT_FAIL'

export const AUTH_LOAD_SUCCESS = 'AUTH_LOAD_SUCCESS'

export const UPDATE_VIEWPORT = 'UPDATE_VIEWPORT'
export const DISALLOW_VIEWPORT_CHANGE = 'DISALLOW_VIEWPORT_CHANGE'
export const SET_USER_VIEWPORT = 'SET_USER_VIEWPORT'
